services:
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: ollama_c

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_c
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_c
    depends_on:
      - server
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules