services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_c
    ports:
      - "11434:11434"
    # Pull the model then start daemon
    command: ["sh", "-c", "ollama pull deepseek-r1:1.5b && ollama daemon"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/v1/models"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_c
    depends_on:
      ollama:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_c
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server